### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Leo225** [Qihoo360/qbusbridge#9]
python producer.py /home/work/qbusbridge/config/kafka.ini mini_spider_struct_data groupid_test ip1:port1,ip2:port2,ip3:port3
Traceback (most recent call last):
  File "producer.py", line 1, in <module>
    import qbus
  File "/home/work/qbusbridge/python/examples/qbus.py", line 26, in <module>
    _qbus = swig_import_helper()
  File "/home/work/qbusbridge/python/examples/qbus.py", line 22, in swig_import_helper
    _mod = imp.load_module('_qbus', fp, pathname, description)
ImportError: /home/work/qbusbridge/python/examples/_qbus.so: undefined symbol: _ZTVN6snappy22UncheckedByteArraySinkE

**Comment by BewareMyPower** [comment]
It looks like you're using an outdated snappy. Tips, the default snappy on CentOS 7 is too old. You should install a newer snappy as the dependency.
